### ISSUE TITLE
Is this compatible with ESP-IDF release/v4.1 and release/v3.3?

### ISSUE THREAD

**Issue by sagar448** [espressif/esp-now#13]
We would like to integrate this into our projects which are currently based on release 4.1 and 3.3. Would this be compatible with those versions?

Thanks!

**Comment by LJYSP** [comment]
This project is compatible with release v4.3, not compatible with release 4.1 and 3.3. Because some apis are not the same, like console  api in components/debug, led api in examples/dev_kits/common_components/led.

what functions do you will use in espnow, you may try to change the api to your  IDF version.

**Comment by Raghav3107** [comment]
Hello @LJYSP 

Does this project work with the idf v4.2.2 ? Can we directly use the components ? 
Does the Components utils are based on the v4.3 ??

**Comment by lhespress** [comment]
@sagar448 Please refer to the instructions of [idf-version](https://github.com/espressif/esp-now/#idf-version) and checkout it to the master branch.
