### ISSUE TITLE
is comunication is low power?

### ISSUE THREAD

**Issue by mrdsn3** [espressif/esp-now#27]
When I use the program related to this technology, the device gets hot, it seems to consume a lot of power, and for this reason, it gets hot. Does this connection really consume low power?
so why  device gets hot after few mins

**Comment by LJYSP** [comment]
What program do you use? When the device gets hot, is it sending packets all the time ?
For the update readme, we remove the low power, because currently we didn't open the wifi power save, that is the RF  is always on. We will add wifi power save function in esp-now in the future.
If your device sends packets every few minutes,  you may make the device in deep sleep after sending and wake up before the next sending to achieve low power. Refer to https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32/api-reference/system/sleep_modes.html?highlight=deep_sleep#entering-deep-sleep

**Comment by mrdsn3** [comment]
thanks best regards
