### ISSUE TITLE
Problem downloading coin_cell_demo using create-project-from-example command (AEGHB-239)

### ISSUE THREAD

**Issue by rglissmann** [espressif/esp-now#76]
I am trying to download the coin_cell_demo example using the command: 
idf.py create-project-from-example "espressif/esp-now=*:coin_cell_demo" 
and I get the following error: 
ERROR: Cannot find example "coin_cell_demo" for "espressif/esp-now" version "=*"

I don't have a problem downloading the other esp-now examples using this command.

**Comment by wujiangang** [comment]
Hi @rglissmann Thanks for your report, the command should be `idf.py create-project-from-example "espressif/esp-now=*:coin_cell_demo/bulb"` or `idf.py create-project-from-example "espressif/esp-now*:coin_cell_demo/switch"`, since coin_cell_demo is not the actual example. The README will be fixed later.

**Comment by rglissmann** [comment]
Thanks for your quick response. One correction, a missing = sign. idf.py create-project-from-example "espressif/esp-now=*:coin_cell_demo/switch"
